### ISSUE TITLE
How to use a writeOnly atom in atomsMutation ?

### ISSUE THREAD

**Issue by TeaBough** [jotai-labs/jotai-tanstack-query#13]
I can't find a way to use a write only atom in `atomsMutations` since we can only use the getter...
Is there another way to do that ?

**Comment by dai-shi** [comment]
Hm, but you shouldn't mutate things in read functions. That's why read functions only get getters, no setters. You want to share some use cases?

**Comment by TeaBough** [comment]
For instance, when there is an error calling the api I'd like to raise an popup error (using a `notifyErrorAtom`).
The other use case is with undo redo. When I change data in the backend I store in an atom the history of the object allowing the user to undo redo. I have for instance an `addToPastAtom`, `resetFutureAtom` and `setFutureAtom` that are write-only, and I can't use them in `atomsMutations`.

**Comment by dai-shi** [comment]
Wait, atomsWithMutation creates writable atoms. You can create a new atom using them as well as `addToPastAtom`. I guess your point is that you need to use the result of mutation? That sounds impossible _for now_.

**Comment by TeaBough** [comment]
Thus, how can I use the writable atoms I get from `atomsWithMutation` in another atom. If I've understand correctly I can do something like that : 

```
const [, mutateQueryAtom] = atomsWithMutation(....)
export const mutateAtom = atom(
null,
(_get, set, params) => {
   const result = set(mutateQueryAtom, params)
   if (result.error) {
          set(notifyErrorAtom, { message: 'ERROR' })
          return;
   }
   set(addToPastAtom, oldItem);
}
)
``

**Comment by dai-shi** [comment]
`set` can't return values. it's return type is just `void | Promise<void>`.

```js
const [, mutateQueryAtom] = atomsWithMutation(....)
export const mutateAtom = atom(
  null,
  async (get, set, params) => {
     await set(mutateQueryAtom, params)
     // I'm not sure if this is available soon enough. Please have a try
     const result = get(mutateQueryAtom)
     if (result.error) {
            set(notifyErrorAtom, { message: 'ERROR' })
            return;
     }
     set(addToPastAtom, oldItem);
   })
```

**Comment by TeaBough** [comment]
Alright, but I'm still getting this error : 
```
atomsWithMutation.ts:43 Uncaught (in promise) TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
    at atomsWithMutation.ts:43:22
```
coming from this `await set(mutateQueryAtom, params)`

**Comment by TeaBough** [comment]
Here is my atomsWithMutations : 
```
const [, updateProgrammationQueryAtom] = atomsWithMutation<
  Partial<Programmation>,
  AxiosError,
  Partial<Programmation>
>(get => {
  const { schoolyearId, schoolId } = get(schoolyearSchoolAtom);
  const queryClient = get(queryClientAtom);
  const programmationId = get(programmationIdAtom);

  const oldProg = get(progDataAtom);

  if (!oldProg) {
    return;
  }
  return {
    mutationFn: params => {
      return update({
        schoolyearId,
        schoolId,
        programmation: { ...oldProg, ...params },
      });
    },
    onMutate: programmation => {
      queryClient.setQueryData<Programmation>(
        [schoolyearId, schoolId, PROGRAMMATION_KEY, programmationId],
        programmation,
      );
    },
  };
});
```

**Comment by dai-shi** [comment]
oops, action has to be an array.
https://github.com/jotai-labs/jotai-tanstack-query/blob/4279118951c58ad8f794fc50458ecf38327e1afb/src/atomsWithMutation.ts#L11-L14
this is unavoidable for now.

```js
  await set(mutateQueryAtom, [params])
```

**Comment by TeaBough** [comment]
Nice 👍 Sorry I must have missed that part in the doc.
