### ISSUE TITLE
what's this repo for?

### ISSUE THREAD

**Issue by stimw** [jotai-labs/jotai-tanstack-query#15]
Hi, 

I'm new to jotai.

I noticed the jotai github doc doesn't include this anymore: https://github.com/pmndrs/jotai/blob/v1.7.7/docs/integrations/query.mdx

Meanwhile, the [official website doc](https://jotai.org/docs/integrations/query) contains this.

I'm a little confused

**Comment by dai-shi** [comment]
`jotai/query` will be deprecated soon and will be removed in jotai v2. `jotai-tanstack-query` is the new implementation of it with more features and stability.
